theme: jekyll-theme-hacker
title: Xoltrons Cool Website!
description: Welcome to my website. This has a bunch of cool stuff about me, some games, and other crazy stuff I put on here when I get bored.
discord_username: XoltronMaster#4522
tiktok_username: XoltronMaster
